/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Apresentacao;

import Controle.Observer;
import Dados.Sessao;
import java.util.ArrayList;

/**
 *
 * @author Felipe.f
 */
public class CartazHelper extends javax.swing.JPanel implements Observer {
    private ArrayList<Sessao> sessoes = new ArrayList<Sessao>();
    
    /**
     * Creates new form CartazHelper
     */
    
    public CartazHelper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    
    private void atualizaCartaz(){
        for(Sessao se: sessoes){
            SessaoHelper sessao;
            sessao = new SessaoHelper(se.getFilme(), se.getSala(),se.getData());
            this.add(sessao);
            this.repaint();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object obj) {
        this.sessoes = (ArrayList<Sessao>)obj;
        this.atualizaCartaz();
    }
}
